version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file SamTemplateP1.yaml --s3-bucket search_photos --output-template-file outputTemplateP1.yaml
artifacts:
  type: zip
  files:
    - SamTemplateP1.yaml
    - outputTemplateP1.yaml
